// Mock data shown to nbtech demo user — no real lead or contact data

export const MOCK_LEADS = [
  { id: 'mock-1', firstName: 'James', lastName: 'Mitchell', email: 'james.mitchell@example.com', phone: '(312) 555-0142', city: 'Chicago', state: 'IL', status: 'prospect', leadType: 'nb_tech', engagementScore: 82, starRating: 4, callAttempts: 3, leadPipelineStage: 'preclose', leadPipelineOwner: 'nbtech', lastCalledAt: new Date(Date.now() - 2 * 3600000).toISOString(), bestTimeToCall: 'Mornings', ageCategory: '50s' },
  { id: 'mock-2', firstName: 'Sandra', lastName: 'Flores', email: 'sandra.flores@example.com', phone: '(713) 555-0298', city: 'Houston', state: 'TX', status: 'prospect', leadType: 'nb_tech', engagementScore: 67, starRating: 3.5, callAttempts: 2, leadPipelineStage: 'callback', leadPipelineOwner: 'nbtech', lastCalledAt: new Date(Date.now() - 5 * 3600000).toISOString(), bestTimeToCall: 'Afternoons', ageCategory: '40s' },
  { id: 'mock-3', firstName: 'Robert', lastName: 'Nguyen', email: 'robert.nguyen@example.com', phone: '(415) 555-0371', city: 'San Francisco', state: 'CA', status: 'lead', leadType: 'standard', engagementScore: 41, starRating: 2, callAttempts: 1, leadPipelineStage: 'reviewing', leadPipelineOwner: 'nbtech', lastCalledAt: null, bestTimeToCall: 'Evenings', ageCategory: '60s' },
  { id: 'mock-4', firstName: 'Patricia', lastName: 'Coleman', email: 'p.coleman@example.com', phone: '(602) 555-0184', city: 'Phoenix', state: 'AZ', status: 'prospect', leadType: 'standard', engagementScore: 59, starRating: 3, callAttempts: 4, leadPipelineStage: 'read', leadPipelineOwner: 'nbtech', lastCalledAt: new Date(Date.now() - 24 * 3600000).toISOString(), bestTimeToCall: 'After 2pm', ageCategory: '70s' },
  { id: 'mock-5', firstName: 'David', lastName: 'Okafor', email: 'dokafor@example.com', phone: '(404) 555-0267', city: 'Atlanta', state: 'GA', status: 'intro_email_sent', leadType: 'nb_tech', engagementScore: 24, starRating: 1, callAttempts: 1, leadPipelineStage: 'reviewing', leadPipelineOwner: 'nbtech', lastCalledAt: null, bestTimeToCall: 'Mornings', ageCategory: '50s' },
  { id: 'mock-6', firstName: 'Karen', lastName: 'Whitfield', email: 'kwhitfield@example.com', phone: '(214) 555-0319', city: 'Dallas', state: 'TX', status: 'opened_intro_email', leadType: 'standard', engagementScore: 38, starRating: 2.5, callAttempts: 2, leadPipelineStage: 'reviewing', leadPipelineOwner: 'nbtech', lastCalledAt: new Date(Date.now() - 48 * 3600000).toISOString(), bestTimeToCall: 'Weekends', ageCategory: '40s' },
  { id: 'mock-7', firstName: 'Michael', lastName: 'Torres', email: 'm.torres@example.com', phone: '(305) 555-0448', city: 'Miami', state: 'FL', status: 'prospect', leadType: 'nb_tech', engagementScore: 91, starRating: 5, callAttempts: 5, leadPipelineStage: 'load', leadPipelineOwner: 'nbtech', lastCalledAt: new Date(Date.now() - 1 * 3600000).toISOString(), bestTimeToCall: 'Mornings', ageCategory: '60s' },
  { id: 'mock-8', firstName: 'Linda', lastName: 'Park', email: 'lpark@example.com', phone: '(206) 555-0533', city: 'Seattle', state: 'WA', status: 'lead', leadType: 'standard', engagementScore: 15, starRating: 1, callAttempts: 0, leadPipelineStage: 'reviewing', leadPipelineOwner: 'nbtech', lastCalledAt: null, bestTimeToCall: 'No preference', ageCategory: '30s' },
];

export const MOCK_INVESTORS = [
  { id: 'mock-inv-1', name: 'Thomas Harrington', username: 'tharrington', email: 'thomas.h@example.com', phone: '(312) 555-9901', company: 'Harrington Capital', status: 'investor', disposition: 'active', investmentAmount: 50000, investmentDate: '2025-11-15', starRating: 5, engagementScore: 94, pipelineStage: 'load', pipelineOwner: 'nbtech', role: 'investor' },
  { id: 'mock-inv-2', name: 'Angela Reyes', username: 'areyes', email: 'areyes@example.com', phone: '(713) 555-4422', company: '', status: 'prospect', disposition: 'active', investmentAmount: 25000, starRating: 4, engagementScore: 72, pipelineStage: 'preclose', pipelineOwner: 'nbtech', role: 'investor' },
  { id: 'mock-inv-3', name: 'William Chen', username: 'wchen', email: 'wchen@example.com', phone: '(415) 555-7731', company: 'Pacific Ventures', status: 'prospect', disposition: 'callback', callbackAt: new Date(Date.now() + 2 * 3600000).toISOString(), investmentAmount: 15000, starRating: 3, engagementScore: 45, pipelineStage: 'callback', pipelineOwner: 'nbtech', role: 'investor' },
  { id: 'mock-inv-4', name: 'Donna Simmons', username: 'dsimmons', email: 'dsimmons@example.com', phone: '(602) 555-3318', company: '', status: 'investor', disposition: 'active', investmentAmount: 75000, investmentDate: '2025-12-03', starRating: 5, engagementScore: 88, pipelineStage: 'load', pipelineOwner: 'nbtech', role: 'investor' },
];