/**
 * ClosingModules.js — Step-by-step modules for a perfect debt-settlement close.
 * Derived from the MasterScript: intro → discovery → credit pull → quote →
 * budget → enrollment → docs/sign → QC transfer. Each module has checkable
 * steps and fields the closer must capture.
 */
export const CLOSING_MODULES = [
  {
    id: 'intro',
    title: 'Intro & Credentials',
    icon: '👋',
    steps: [
      'Greet: "Debt Advisors, this is [Name]"',
      'Confirm they can hear you okay',
      'State name + title: Licensed Debt Specialist',
      'Explain purpose: state/federal debt relief options, 30-40% reduction, zero interest on remainder',
      'Send credentials email + business card text',
      'Mention A+ BBB rating, USA Today feature, $80M saved last year',
      'Ask: handle finances with spouse / family member? Who pays the cards?',
    ],
    capture: ['Email address', 'Credentials email sent', 'Business card texted'],
  },
  {
    id: 'discovery',
    title: 'Discovery & Hardship',
    icon: '🔍',
    steps: [
      'Ask how card balances got to this point (inflation, COVID, loss of income, unexpected expenses)',
      'Confirm: stuck paying interest, not seeing light at end of tunnel',
      'Ask: looked into options before or first time?',
      'Ask: payments manageable? Still using accounts or paying down?',
      'Ask: able to put anything into savings after payments?',
      'Ask: how much of payments going to interest?',
      'Capture the hardship story (when / why / how)',
    ],
    capture: ['Hardship summary', 'Co-finances?', 'Interest burden noted'],
  },
  {
    id: 'credit',
    title: 'Credit Pull & Account Review',
    icon: '📊',
    steps: [
      'Verify address on file',
      'Mention letters sent in mail (recycle bin line)',
      'Get permission to pull accounts — no inquiry, no credit hit',
      'Verify date of birth',
      'Verify last 4 of SSN (security)',
      'Review revolving utilization %',
      'List each account: creditor, balance, minimum payment',
      'Confirm total eligible debt + current monthly payments',
      'Show 15-year payoff reality at current interest',
      'Ask: plan major financing soon? Using credit for anything?',
    ],
    capture: ['DOB', 'Last 4 SSN', 'Total eligible debt', 'Current monthly payments', 'Utilization %'],
  },
  {
    id: 'quote',
    title: 'Program Quote & Escrow',
    icon: '💰',
    steps: [
      'Send quote to email',
      'State program term + monthly payment',
      'State monthly relief vs current payments',
      'Explain zero % interest on remaining balance',
      'Explain 30-40% reduction via creditor tax write-off',
      'Explain FDIC-insured escrow account (like mortgage)',
      'Explain settlement flow: offer → your approval → structured settlement',
      'Trade-off: enrolled cards close, move recurring charges to debit',
      'Credit restoration: score rises as debt-to-income drops',
      'No prepayment penalty — extra deposits shorten program',
      'Fees already factored into monthly payment (flat, state-regulated)',
      'We take over all creditor communication — no more min payments',
    ],
    capture: ['Program term (months)', 'Program payment', 'Monthly relief', 'Fee schedule quoted'],
  },
  {
    id: 'budget',
    title: 'Budget Verification',
    icon: '🧮',
    steps: [
      'Take-home income (after taxes/deductions)',
      'Rent or mortgage',
      'Utilities',
      'HOA / homeowners insurance',
      'Car payment + insurance',
      'Gas + maintenance',
      'Groceries',
      'Medical insurance out of pocket',
      'Confirm surplus after program payment',
      'Repeat hardship summary for underwriting',
      'Ask: anything else to mention for underwriting?',
    ],
    capture: ['Monthly income', 'Total expenses', 'Surplus', 'Employer / occupation'],
  },
  {
    id: 'enroll',
    title: 'Enrollment & Banking',
    icon: '✍️',
    steps: [
      'Pause payments to enrolled creditors; deactivate auto-pay',
      'Get middle initial',
      'Set security question: mother\'s maiden name',
      'Pick payment day (no food off the table)',
      'Get bank name + validate',
      'Verify first 5 of SSN (confirm right person)',
      'Add notes for underwriting',
    ],
    capture: ['Payment day', 'Bank', 'Middle initial', 'Mother\'s maiden'],
  },
  {
    id: 'docs',
    title: 'Docs, Sign & Contact Info',
    icon: '📋',
    steps: [
      'Give contact info: name (spell last), desk number, email',
      'Send DNC link (FTC Do Not Call Registry) — confirm registration',
      'Send program agreements (email + text)',
      'DocuSign walkthrough: e-sign consent → Next → sign here → adopt & sign → initial',
      'Authorization to Communicate (Start New Financial)',
      'Escrow account with Global Holdings',
      'Evergreen Legal Protection (summons / legal doc coverage)',
      'Satisfaction money-back guarantee + legal protection',
      'Mention 1099 / 982 insolvency form',
      'Click Finish & Submit',
      'Confirm signed copy in inbox',
    ],
    capture: ['Desk number given', 'DNC sent', 'Docs sent', 'DocuSign walked'],
  },
  {
    id: 'transfer',
    title: 'Transfer to QC',
    icon: '🤝',
    steps: [
      'Congratulate the client',
      'Explain QC handoff: Start New Financial goes over script + accept settlements',
      'Mention settlement amounts (40% off typical, 20% Amex/Discover)',
      'Mention 3-7 month first settlement timeline',
      'Mention online client dashboard for tracking',
      'Schedule follow-up call next week',
      'Transfer + wish them luck',
    ],
    capture: ['Follow-up scheduled', 'Transferred to QC'],
  },
];